// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file stratsync.proto (package stratsync, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ClearOtherSessionsRequest, ElevationRequest, EventResponse, MutateEntriesRequest, SubscriptionRequest, UpdatePlayerJobRequest, UpsertDamageOptionRequest } from "./stratsync_pb";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service stratsync.StratSync
 */
export const StratSync = {
  typeName: "stratsync.StratSync",
  methods: {
    /**
     * @generated from rpc stratsync.StratSync.Event
     */
    event: {
      name: "Event",
      I: SubscriptionRequest,
      O: EventResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc stratsync.StratSync.ClearOtherSessions
     */
    clearOtherSessions: {
      name: "ClearOtherSessions",
      I: ClearOtherSessionsRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc stratsync.StratSync.Elevate
     */
    elevate: {
      name: "Elevate",
      I: ElevationRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc stratsync.StratSync.UpsertDamageOption
     */
    upsertDamageOption: {
      name: "UpsertDamageOption",
      I: UpsertDamageOptionRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc stratsync.StratSync.MutateEntries
     */
    mutateEntries: {
      name: "MutateEntries",
      I: MutateEntriesRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc stratsync.StratSync.UpdatePlayerJob
     */
    updatePlayerJob: {
      name: "UpdatePlayerJob",
      I: UpdatePlayerJobRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

