// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file stratsync.proto (package stratsync, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  DeleteEntryRequest,
  DeletePlayerRequest,
  ElevationRequest,
  EventResponse,
  InsertPlayerRequest,
  SubscriptionRequest,
  UpsertDamageOptionRequest,
  UpsertEntryRequest,
} from './stratsync_pb';
import { Empty, MethodKind } from '@bufbuild/protobuf';

/**
 * @generated from service stratsync.StratSync
 */
export const StratSync = {
  typeName: 'stratsync.StratSync',
  methods: {
    /**
     * @generated from rpc stratsync.StratSync.Event
     */
    event: {
      name: 'Event',
      I: SubscriptionRequest,
      O: EventResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc stratsync.StratSync.Elevate
     */
    elevate: {
      name: 'Elevate',
      I: ElevationRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc stratsync.StratSync.UpsertDamageOption
     */
    upsertDamageOption: {
      name: 'UpsertDamageOption',
      I: UpsertDamageOptionRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc stratsync.StratSync.UpsertEntry
     */
    upsertEntry: {
      name: 'UpsertEntry',
      I: UpsertEntryRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc stratsync.StratSync.DeleteEntry
     */
    deleteEntry: {
      name: 'DeleteEntry',
      I: DeleteEntryRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc stratsync.StratSync.InsertPlayer
     */
    insertPlayer: {
      name: 'InsertPlayer',
      I: InsertPlayerRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc stratsync.StratSync.DeletePlayer
     */
    deletePlayer: {
      name: 'DeletePlayer',
      I: DeletePlayerRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  },
} as const;
