import type {Metadata} from 'next';
import localFont from 'next/font/local';
import './globals.css';
import {cn} from '@/lib/utils';

const pretendard = localFont({
	src: '../../public/fonts/PretendardVariable.woff2',
	display: 'swap',
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): React.ReactElement {
	return (
		<html lang='en'>
			<body className={cn('min-h-screen bg-backgroun font-sans antialiased', pretendard.className)}>{children}</body>
		</html>
	);
}
